//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCustomerData
    {
        public int Id { get; set; }
        public string CustomerNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Curcd { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Company_yn { get; set; }
        public string Freeze_yn { get; set; }
        public string Obu { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
